version: '3.9'

services:
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "7000:7000"
    restart: unless-stopped

  api-gateway-1:
    build: ./api-gateway
    container_name: api-gateway-1
    restart: unless-stopped

  api-gateway-2:
    build: ./api-gateway
    container_name: api-gateway-2
    restart: unless-stopped

  web-shell:
    build: ./web-shell
    container_name: web-shell
    volumes:
      - web_shell_build:/var/www/web-shell
    restart: unless-stopped


  web-admin:
    build: ./web-admin
    container_name: web-admin
    volumes:
      - web_admin_build:/var/www/web-admin
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - api-gateway-1
      - api-gateway-2
      - notification-service
      - web-shell
      - web-admin
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - web_shell_build:/var/www/web-shell
      - web_admin_build:/var/www/web-admin
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  email-worker:
    build: ./email-worker
    container_name: email-worker
    depends_on:
      - rabbitmq
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    restart: unless-stopped

  task-events-consumer:
    build: ./task-events-consumer
    container_name: task-events-consumer
    depends_on:
      - kafka
    restart: unless-stopped

  postgres:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: taskuser
        POSTGRES_PASSWORD: taskpass
        POSTGRES_DB: taskdb
      ports:
        - "5432:5432"
      restart: unless-stopped


  faas-service:
      build: ./faas-service
      container_name: faas-service
      restart: unless-stopped


volumes:
  web_shell_build:
  web_admin_build:



